[tool.black]
line-length = 98
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 98
known_first_party = ["gpw-quant-system"]

[tool.ruff]
line-length = 98
exclude = ["**/*.ipynb"]
select = ["E", "F", "W", "C", "I", "T"]
